stages:
  - build
  - release

variables:
  NODE_VERSION: "18.18.2"

build:
  stage: build
  image: node:${NODE_VERSION}
  only:
    - tags
  before_script:
    - apt-get update && apt-get install -y curl git maven openjdk-17-jdk
    - npm install
  script:
    - DISABLE_ESLINT_PLUGIN=true npm run build
    - DISABLE_ESLINT_PLUGIN=true npx keycloakify
    - mv build_keycloak/target/retrocompat-*.jar build_keycloak/target/retrocompat-keycloak-theme.jar || true
    - mv build_keycloak/target/astrago-*.jar build_keycloak/target/keycloak-theme.jar || true
  artifacts:
    paths:
      - build_keycloak/target/keycloak-theme.jar
    expire_in: 1 h  # 1시간 후 자동 삭제

release:
  stage: release
  image: curlimages/curl:latest
  only:
    - tags
  script:
    - |
      curl --request POST \
        --header "PRIVATE-TOKEN: $GITLAB_TOKEN" \
        --form "name=Release $CI_COMMIT_TAG" \
        --form "tag_name=$CI_COMMIT_TAG" \
        --form "description=- GitLab CI에서 자동으로 생성됨" \
        "http://10.61.3.134/api/v4/projects/$CI_PROJECT_ID/releases"

      curl --request POST \
        --header "PRIVATE-TOKEN: $GITLAB_TOKEN" \
        --form "file=@build_keycloak/target/keycloak-theme.jar" \
        "http://10.61.3.134/api/v4/projects/$CI_PROJECT_ID/uploads" > response.json

      ASSET_URL=$(sed -n 's/.*"url":"\([^"]*\)".*/\1/p' response.json)

      curl --request POST \
        --header "PRIVATE-TOKEN: $GITLAB_TOKEN" \
        --data "name=keycloak-theme.jar&url=http://10.61.3.134/$CI_PROJECT_PATH$ASSET_URL" \
        "http://10.61.3.134/api/v4/projects/$CI_PROJECT_ID/releases/$CI_COMMIT_TAG/assets/links"